name: flutter_common_extensions_flutterfly
description: A comprehensive collection of useful Flutter extensions for everyday development. Includes extensions for Widget, String, DateTime, Color, List, Duration and more.
version: 1.0.0
homepage: https://github.com/yourusername/flutter_common_extensions
repository: https://github.com/yourusername/flutter_common_extensions
issue_tracker: https://github.com/yourusername/flutter_common_extensions/issues

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0

  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
